#
DEFINES = NDEBUG ARM_ALLOW_MULTI_CORE SD_WRITE_SUPPORT
#
EXTRA_SRCDIR = arm arm/aeabi device/mmc device/emac device/fb net
#
EXTRA_INCLUDES = ../lib-ff12c/src
#
include ../h3-firmware-template/lib/Rules.mk
